import pygame, sys, random
from pygame import draw

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 480, 480
GRIDSIZE=20
GRID_WIDTH = SCREEN_HEIGHT/GRIDSIZE
GRID_HEIGHT = SCREEN_WIDTH/GRIDSIZE
UP =(0,-1)
DOWN=(0, 1)
LEFT=(-1,0)
RIGHT =(1,0)

